services:

  applio:
    container_name: applio
    image: iahispano/applio:latest
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8200:6969
    command: ["python3", "app.py", "--open", "--share"]
    tty: true
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]