services:

  applio:
    container_name: applio
    image: iahispano/applio:latest
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ${HF_HOME}:/root/.cache/
      - ${TORCH_HOME}:/root/.cache/huggingfacetorch
    ports:
      - ${APPLIO_PORT}:6969
    command: ["python3", "app.py", "--open", "--share"]
    tty: true
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]